# Generated by Django 4.2.6 on 2023-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0009_remove_plant_contributor_plant_contraindications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='contraindications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cultural_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='economical_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='health_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='other_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='preparation_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='social_value',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
