# Generated by Django 4.2.6 on 2023-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0010_alter_plant_contraindications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='region_in_Uganda',
            field=models.CharField(choices=[('northern_uganda', 'northern_uganda'), ('eastern_uganda', 'eastern_uganda'), ('western_uganda', 'western_uganda'), ('central_uganda', 'central_uganda')], max_length=100, null=True),
        ),
    ]
