# Generated by Django 4.2.6 on 2023-11-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0013_alter_plant_region_in_uganda'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='climate_impact',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
