# Generated by Django 4.2.6 on 2023-11-16 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0015_alter_plant_citation_alter_plant_climate_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantname',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_names', to='plants_app.plant'),
        ),
    ]
