# Generated by Django 4.2.6 on 2023-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0016_alter_plantname_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='local_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='names',
            field=models.ManyToManyField(related_name='botanical_name', through='plants_app.PlantName', to='plants_app.language'),
        ),
    ]
