# Generated by Django 4.2.6 on 2023-11-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0017_plant_local_language_plant_name_alter_plant_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='region_in_Uganda',
            field=models.CharField(choices=[('Northern Uganda', 'Northern Uganda'), ('Eastern Uganda', 'Eastern Uganda'), ('Western Uganda', 'Western Uganda'), ('Central Uganda', 'Central Uganda')], max_length=100, null=True),
        ),
    ]
